import InputForm from "./components/InputForm";
import GcodePreview from "./components/GcodePreview";
import GcodeDownload from "./components/GcodeDownload";
import Credits from "./components/Credits";
import TitleLabels from "./components/TitleLabels";
import { SlimAlert } from "./components/Banners";

function App() {
  return (
    <div className=" bg-slate-50">
      <div className="flex max-w-screen-xl">
        <aside className="h-screen sticky top-0 w-96 bg-white drop-shadow overflow-y-scroll shrink-0">
          <div className="m-8">
            <h1 className="text-3xl mb-1 font-bold">Flow Test Generator</h1>
            <TitleLabels />
            <section>
              <h2 className="text-xl mb-2 font-bold">Gcode Preview</h2>
              <GcodePreview />
            </section>

            <section className="mt-4">
              <GcodeDownload />
            </section>

            <section className="mt-4">
              <Credits />
            </section>
          </div>
        </aside>

        <main>
          <div className="m-8">
            <SlimAlert
              title=" Use at your own risk and discretion."
              msg="Verify all generated Gcode from this tool before attempting to print it. You are responsible for any damage caused to your printer as a result of using Gcode generated by this tool. "
            />
            <InputForm />
          </div>
        </main>
      </div>
    </div>
  );
}

export default App;
